import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Activity, HardDrive, Network,
    ChevronDown, ChevronUp, Cpu, Database
} from 'lucide-react';



const patterns = [
    {
        id: 'ptc',
        title: 'Programmatic Tool Calling (PTC)',
        icon: <Cpu size={28} color="var(--accent-gold)" />,
        content: 'Instead of feeding million-line CSV files into the LLM context, LangAlpha uses Daytona cloud sandboxes to create independent workspaces. The agent receives the data schema and dynamically writes Python or Node code loops. The backend runs this out-of-band and returns aggregate metrics or visual charts directly back to the context. This massively saves tokens and solves "lost in the middle" hallucination problems.'
    },
    {
        id: 'swarm',
        title: 'Async Agent Swarm',
        icon: <Network size={28} color="var(--accent-gold)" />,
        content: 'When the Orchestrator hits a latency bottleneck (e.g. parsing 10 years of SEC balance sheets), it dynamically makes a tool call to initialize an isolated background subagent. The user remains unblocked and can continue chatting with the Orchestrator (often via flash models to minimize latency), while background workers steadily push artifacts to the filesystem.'
    },
    {
        id: 'streaming',
        title: 'Middlewares & Streaming SSE',
        icon: <Activity size={28} color="var(--accent-gold)" />,
        content: 'Standard HTTP request-response cycles fail under the large volume of nested reasoning generated by LangGraph. Every graph hop continuously pushes events (tokens, tool lifecycle, subagent logs) over Server-Sent Events (SSE). Redis acts as a safety buffer. If a mobile browser disconnects, it reconnects and restores the message tree perfectly starting from the missing event id.'
    },
    {
        id: 'context',
        title: 'Persistent Context in Independent Environment',
        icon: <Database size={28} color="var(--accent-gold)" />,
        content: 'LangAlpha creates a full IDE environment instead of a simple chat box. Workspaces sync persistent Linux virtual filesystems locally. When analyzing for subsequent prompts, the agent natively runs grep tools over its previously generated Markdown summaries saved to the filesystem rather than calling massive remote APIs again.'
    }
];

const ArchitectureSection = () => {
    const [expandedPattern, setExpandedPattern] = useState(patterns[0].id);

    return (
        <section style={{
            padding: '100px 0 60px 0',
            position: 'relative'
        }}>
            <motion.div
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.8 }}
                style={{ width: '100%' }}
            >

                {/* 2. Architectural Patterns Layout */}
                <div>
                    <h3 style={{ fontSize: '1.5rem', marginBottom: '2rem', color: 'var(--text-main)', textAlign: 'center' }}>
                        Core Infrastructure Patterns
                    </h3>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                        {patterns.map((pattern) => {
                            const isExpanded = expandedPattern === pattern.id;

                            return (
                                <motion.div
                                    key={pattern.id}
                                    className="minimal-panel"
                                    style={{ padding: '0', overflow: 'hidden' }}
                                >
                                    <div
                                        onClick={() => setExpandedPattern(isExpanded ? null : pattern.id)}
                                        style={{
                                            padding: '25px',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'space-between',
                                            cursor: 'pointer',
                                            background: isExpanded ? 'rgba(252, 211, 77, 0.05)' : 'transparent'
                                        }}
                                    >
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
                                            {pattern.icon}
                                            <h4 style={{ margin: 0, fontSize: '1.2rem', color: isExpanded ? 'var(--accent-gold)' : 'var(--text-main)', transition: 'color 0.3s ease' }}>
                                                {pattern.title}
                                            </h4>
                                        </div>
                                        <div style={{ color: isExpanded ? 'var(--accent-gold)' : 'var(--text-muted)' }}>
                                            {isExpanded ? <ChevronUp size={24} /> : <ChevronDown size={24} />}
                                        </div>
                                    </div>

                                    <AnimatePresence>
                                        {isExpanded && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.3, ease: 'easeInOut' }}
                                            >
                                                <div style={{
                                                    padding: '0 25px 25px 83px',
                                                    color: 'var(--text-muted)',
                                                    lineHeight: 1.7,
                                                    fontSize: '1.05rem'
                                                }}>
                                                    {pattern.content}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </motion.div>
                            );
                        })}
                    </div>
                </div>

            </motion.div>
        </section>
    );
};

export default ArchitectureSection;
