import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Server, BrainCircuit, Terminal,
    Wrench, Activity, HardDrive, Network,
    ChevronDown, ChevronUp, Cpu, Database
} from 'lucide-react';

const architectureNodes = [
    {
        id: 'client',
        title: 'Client Layer',
        subtitle: 'Web UI & CLI Interfaces',
        icon: <Terminal size={24} />,
        description: 'The rich interactive entrypoints. Houses the modern SPA Workspace UI handling multiple user sessions, and a separate TUI/CLI for developer-heavy interactions.',
        details: [
            'React / Vite SPA Frontend.',
            'Interactive Charting for native tool rendering.',
            'Real-time Subagents Dashboard for parallel observability.'
        ]
    },
    {
        id: 'gateway',
        title: 'Gateway & Backend Layer',
        subtitle: 'FastAPI, Postgres, & Redis',
        icon: <Server size={24} />,
        description: 'The central nervous system routing requests, streaming real-time artifacts via Server-Sent Events (SSE), and persisting agent states.',
        details: [
            'FastAPI Async Python Server backend.',
            'PostgreSQL handles Auth, Watchlists, and States.',
            'Redis Pub/Sub buffers the SSE stream ensuring no dropped packages.'
        ]
    },
    {
        id: 'agent',
        title: 'Agent Core Layer',
        subtitle: 'LangGraph & Gemini Models',
        icon: <BrainCircuit size={24} />,
        description: 'The cognitive driver utilizing a cyclical graph state-machine. Implements the orchestrator pattern capable of deeply nested programmatic reasoning.',
        details: [
            'Main Orchestrator Agent handles long-running goals.',
            'Async Subagent Swarm offloads deep background tasks.',
            'Dynamic middlewares inject multi-modal context and summarize history.'
        ]
    },
    {
        id: 'execution',
        title: 'Execution & Tooling',
        subtitle: 'Daytona, MCP & Native',
        icon: <Wrench size={24} />,
        description: 'The reality layer. Where the cognitive plan interacts with live data grids, dynamic code sandboxes, and specific contextual skills.',
        details: [
            'Daytona Cloud Sandboxes for secure Programmatic Tool Calling.',
            'Model Context Protocol (MCP) servers efficiently pipe bulk data.',
            'Dynamic plugins lazily-load specialized financial capabilities.'
        ]
    }
];

const patterns = [
    {
        id: 'ptc',
        title: 'Programmatic Tool Calling (PTC)',
        icon: <Cpu size={28} color="var(--accent-gold)" />,
        content: 'Instead of feeding million-line CSV files into the LLM context to be read, LangAlpha leverages Daytona cloud sandboxes. The agent receives the data schema and dynamically writes Python or Node code loops. The backend runs this out-of-band and returns aggregate metrics or visual charts directly back to the context. This massively saves tokens and defeats "lost in the middle" hallucination tendencies.'
    },
    {
        id: 'swarm',
        title: 'Async Agent Swarm',
        icon: <Network size={28} color="var(--accent-gold)" />,
        content: 'When the Orchestrator hits a latency bottleneck (e.g. parsing 10 years of SEC balance sheets), it dynamically tools a Task() that spins up an isolated background Subagent. The user remains unblocked and can continue conversing with the Orchestrator (often via speed-optimized Gemini Flash), while background workers steadily push artifacts to the filesystem.'
    },
    {
        id: 'streaming',
        title: 'Middlewares & Streaming SSE',
        icon: <Activity size={28} color="var(--accent-gold)" />,
        content: 'Standard HTTP request-response cycles fail under the sheer volume of nested reasoning generated by LangGraph. Every graph hop continuously pushes events (tokens, tool lifecycle, subagent logs) over Server-Sent Events (SSE). Redis acts as a safety buffer; if a mobile browser disconnects, it reconnects and restores the message tree perfectly starting from the missing event_id.'
    },
    {
        id: 'context',
        title: 'Persistent Compound Context',
        icon: <Database size={28} color="var(--accent-gold)" />,
        content: 'LangAlpha mirrors a full IDE environment instead of a transient chat box. Workspaces sync persistent Linux virtual filesystems locally. When analyzing subsequent quarters, the agent natively runs `grep` tools over its previously generated Markdown summaries saved to the filesystem rather than re-indexing massive remote APIs.'
    }
];

const ArchitectureSection = () => {
    const [selectedNodeId, setSelectedNodeId] = useState(architectureNodes[0].id);
    const [expandedPattern, setExpandedPattern] = useState(patterns[0].id);

    const selectedNode = architectureNodes.find(n => n.id === selectedNodeId);

    return (
        <section style={{
            padding: '100px 0 60px 0',
            position: 'relative'
        }}>
            <motion.div
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.8 }}
                style={{ width: '100%' }}
            >
                <h2 style={{ fontSize: '2.5rem', marginBottom: '1rem', fontStyle: 'italic', textAlign: 'center' }}>
                    System <span style={{ color: 'var(--accent-gold)', fontStyle: 'normal' }}>Architecture</span>
                </h2>
                <div style={{ width: '60px', height: '2px', background: 'var(--text-main)', margin: '0 auto 4rem auto' }} />

                {/* 1. Component Breakdown Layout */}
                <div style={{ marginBottom: '6rem' }}>
                    <h3 style={{ fontSize: '1.5rem', marginBottom: '2rem', color: 'var(--text-main)', textAlign: 'center' }}>
                        Topology & Component Layers
                    </h3>

                    <div style={{
                        display: 'grid',
                        gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
                        gap: '40px',
                        alignItems: 'start'
                    }}>
                        {/* Interactive Node Selector */}
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                            {architectureNodes.map((node, i) => {
                                const isSelected = node.id === selectedNodeId;
                                return (
                                    <motion.div
                                        key={node.id}
                                        onClick={() => setSelectedNodeId(node.id)}
                                        whileHover={{ scale: 1.02 }}
                                        whileTap={{ scale: 0.98 }}
                                        style={{
                                            padding: '20px',
                                            borderRadius: '12px',
                                            cursor: 'pointer',
                                            display: 'flex',
                                            alignItems: 'center',
                                            gap: '20px',
                                            background: isSelected ? 'rgba(252, 211, 77, 0.1)' : 'var(--bg-alt)',
                                            border: `1px solid ${isSelected ? 'var(--accent-gold)' : 'rgba(255,255,255,0.05)'}`,
                                            transition: 'all 0.3s ease'
                                        }}
                                    >
                                        <div style={{
                                            color: isSelected ? 'var(--accent-gold)' : 'var(--text-muted)',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'center'
                                        }}>
                                            {node.icon}
                                        </div>
                                        <div>
                                            <h4 style={{
                                                margin: 0,
                                                fontSize: '1.1rem',
                                                color: isSelected ? 'var(--accent-gold)' : 'var(--text-main)'
                                            }}>
                                                {node.title}
                                            </h4>
                                            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                                                {node.subtitle}
                                            </span>
                                        </div>
                                    </motion.div>
                                );
                            })}
                        </div>

                        {/* Node Details Panel */}
                        <div className="minimal-panel" style={{
                            padding: '40px',
                            height: '100%',
                            display: 'flex',
                            flexDirection: 'column',
                            minHeight: '350px'
                        }}>
                            <AnimatePresence mode="wait">
                                <motion.div
                                    key={selectedNode.id}
                                    initial={{ opacity: 0, x: 20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: -20 }}
                                    transition={{ duration: 0.3 }}
                                >
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '20px' }}>
                                        <div style={{ color: 'var(--accent-gold)' }}>{selectedNode.icon}</div>
                                        <h3 style={{ margin: 0, fontSize: '1.8rem', color: 'var(--text-main)' }}>
                                            {selectedNode.title}
                                        </h3>
                                    </div>
                                    <p style={{ color: 'var(--text-muted)', lineHeight: 1.8, fontSize: '1.05rem', marginBottom: '30px' }}>
                                        {selectedNode.description}
                                    </p>

                                    <h5 style={{ color: 'var(--accent-gold)', marginBottom: '15px', fontSize: '1rem', letterSpacing: '0.05em' }}>KEY RESPONSIBILITIES:</h5>
                                    <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                        {selectedNode.details.map((detail, idx) => (
                                            <li key={idx} style={{
                                                display: 'flex',
                                                gap: '12px',
                                                alignItems: 'flex-start',
                                                color: 'var(--text-main)',
                                                lineHeight: 1.5,
                                                fontSize: '0.95rem'
                                            }}>
                                                <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--accent-gold)', marginTop: '8px', flexShrink: 0 }} />
                                                <span>{detail}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </motion.div>
                            </AnimatePresence>
                        </div>
                    </div>
                </div>

                {/* 2. Architectural Patterns Layout */}
                <div>
                    <h3 style={{ fontSize: '1.5rem', marginBottom: '2rem', color: 'var(--text-main)', textAlign: 'center' }}>
                        Core Infrastructure Patterns
                    </h3>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                        {patterns.map((pattern) => {
                            const isExpanded = expandedPattern === pattern.id;

                            return (
                                <motion.div
                                    key={pattern.id}
                                    className="minimal-panel"
                                    style={{ padding: '0', overflow: 'hidden' }}
                                >
                                    <div
                                        onClick={() => setExpandedPattern(isExpanded ? null : pattern.id)}
                                        style={{
                                            padding: '25px',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'space-between',
                                            cursor: 'pointer',
                                            background: isExpanded ? 'rgba(252, 211, 77, 0.05)' : 'transparent'
                                        }}
                                    >
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
                                            {pattern.icon}
                                            <h4 style={{ margin: 0, fontSize: '1.2rem', color: isExpanded ? 'var(--accent-gold)' : 'var(--text-main)', transition: 'color 0.3s ease' }}>
                                                {pattern.title}
                                            </h4>
                                        </div>
                                        <div style={{ color: isExpanded ? 'var(--accent-gold)' : 'var(--text-muted)' }}>
                                            {isExpanded ? <ChevronUp size={24} /> : <ChevronDown size={24} />}
                                        </div>
                                    </div>

                                    <AnimatePresence>
                                        {isExpanded && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.3, ease: 'easeInOut' }}
                                            >
                                                <div style={{
                                                    padding: '0 25px 25px 83px',
                                                    color: 'var(--text-muted)',
                                                    lineHeight: 1.7,
                                                    fontSize: '1.05rem'
                                                }}>
                                                    {pattern.content}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </motion.div>
                            );
                        })}
                    </div>
                </div>

            </motion.div>
        </section>
    );
};

export default ArchitectureSection;
